name: json_types
description: Type safe JSON serialization/deserialization for Dart with no code generation or reflection.
version: 2.0.2
repository: https://github.com/JohnSiegel/json_types
issue_tracker: https://github.com/JohnSiegel/json_types/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.5
